[project]
name = "bird-detect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Felipe Pereira Heitmann", email = "felipeph@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=5.0.0.93",
    "rich>=15.0.0",
]

[project.scripts]
bird-detect = "bird_detect:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
